### ISSUE TITLE
Installing node sass fails

### ISSUE THREAD

**Issue by matejdro** [sma11black/hexo-action#13]
I'm directly copying example github action (with changed credentials of course). When running, install dependencies step fails with the 

```
../src/sass_context_wrapper.h:8:10: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
```

<details>
  <summary>Longer log</summary>
  

```
 > node-sass@4.12.0 postinstall /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.17
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.15.4
gyp verb command install [ '14.15.4' ]
gyp verb install input version string "14.15.4"
gyp verb install installing version: 14.15.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 14.15.4
gyp verb ensuring nodedir is created /home/runner/.node-gyp/14.15.4
gyp verb created nodedir /home/runner/.node-gyp
gyp http GET https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp verb extracted file from tarball include/node/common.gypi
gyp verb extracted file from tarball include/node/config.gypi
gyp verb extracted file from tarball include/node/node.h
gyp verb extracted file from tarball include/node/node_api.h
gyp verb extracted file from tarball include/node/js_native_api.h
gyp verb extracted file from tarball include/node/js_native_api_types.h
gyp verb extracted file from tarball include/node/node_api_types.h
gyp verb extracted file from tarball include/node/node_buffer.h
gyp verb extracted file from tarball include/node/node_object_wrap.h
gyp verb extracted file from tarball include/node/node_version.h
gyp verb extracted file from tarball include/node/cppgc/common.h
gyp verb extracted file from tarball include/node/cppgc/custom-space.h
gyp verb extracted file from tarball include/node/cppgc/type-traits.h
gyp verb extracted file from tarball include/node/cppgc/allocation.h
gyp verb extracted file from tarball include/node/cppgc/garbage-collected.h
gyp verb extracted file from tarball include/node/cppgc/heap.h
gyp verb extracted file from tarball include/node/cppgc/liveness-broker.h
gyp verb extracted file from tarball include/node/cppgc/macros.h
gyp verb extracted file from tarball include/node/cppgc/member.h
gyp verb extracted file from tarball include/node/cppgc/persistent.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN32/asm_avx2/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/no-asm/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/no-asm/include/progs.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/no-asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/no-asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/no-asm/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm/include/progs.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm_avx2/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm_avx2/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm_avx2/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm_avx2/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-mips64/asm_avx2/include/progs.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/no-asm/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/no-asm/include/progs.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/no-asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/no-asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/no-asm/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm_avx2/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm_avx2/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm_avx2/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm_avx2/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm_avx2/include/progs.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm/include/progs.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/asm/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64-ARM/no-asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64-ARM/no-asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64-ARM/no-asm/crypto/buildinf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64-ARM/no-asm/include/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64-ARM/no-asm/include/progs.h
gyp verb extracted file from tarball include/node/openssl/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/dso_conf.h
gyp verb extracted file from tarball include/node/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/bn_conf_asm.h
gyp verb extracted file from tarball include/node/openssl/bn_conf_no-asm.h
gyp verb extracted file from tarball include/node/openssl/dso_conf_asm.h
gyp verb extracted file from tarball include/node/openssl/dso_conf_no-asm.h
gyp verb extracted file from tarball include/node/openssl/opensslconf_asm.h
gyp verb extracted file from tarball include/node/openssl/opensslconf_no-asm.h
gyp verb extracted file from tarball include/node/zconf.h
gyp verb extracted file from tarball include/node/zlib.h
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`... 
gyp verb checksum url https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp verb checksum data {"node-v14.15.4-aix-ppc64.tar.gz":"03ac3f7d33f17b762d676988b725c58140b5f9a131c849f9b78cbe7f7f84c234","node-v14.15.4-darwin-x64.tar.gz":"6b0e19e5c2601ef97510f7eb4f52cc8ee261ba14cb05f31eb1a41a5043b0304e","node-v14.15.4-darwin-x64.tar.xz":"3078556d474a3e3cd6845d79577ca78c14a3c0ef78d569ae3644834584235e88","node-v14.15.4-headers.tar.gz":"3eb7d4ec4964b10a48987c35c37b3e7720735cf3b9806fe40a805fa1d49a9c7d","node-v14.15.4-headers.tar.xz":"048e5486c86c8e9396a5b765744fad85b9a3ae5ba99f7dd472b41fee16446233","node-v14.15.4-linux-arm64.tar.gz":"b681bda8eaa1ed2ac85e0ed2c2041a0408963c2198a24da183dc3ab60d93d975","node-v14.15.4-linux-arm64.tar.xz":"b990bd99679158c3164c55a20c2a6677c3d9e9ffdfa0d4a40afe9c9b5e97a96f","node-v14.15.4-linux-armv7l.tar.gz":"ffce90b07675434491361dfc74eee230f9ffc65c6c08efb88a18781bcb931871","node-v14.15.4-linux-armv7l.tar.xz":"bafe4bfb22b046cdda3475d23cd6999c5ea85180c180c4bbb94014920aa7231b","node-v14.15.4-linux-ppc64le.tar.gz":"d8b92d3826b7a04b886da92275a64978431fde1b47cc92de48f5fb16131bebb2","node-v14.15.4-linux-ppc64le.tar.xz":"b2456aa4fbfeeea2aae2a0b969c0fc45c12cd218ca48461c6031f590c2ee8495","node-v14.15.4-linux-s390x.tar.gz":"c13f16657074437fd66f888736260af486df89a7d77d8b323655cee6408a8084","node-v14.15.4-linux-s390x.tar.xz":"29f794d492eccaf0b08e6492f91162447ad95cfefc213fc580a72e29e11501a9","node-v14.15.4-linux-x64.tar.gz":"b51c033d40246cd26e52978125a3687df5cd02ee532e8614feff0ba6c13a774f","node-v14.15.4-linux-x64.tar.xz":"ed01043751f86bb534d8c70b16ab64c956af88fd35a9506b7e4a68f5b8243d8a","node-v14.15.4.pkg":"86e42bb639ea69165a1527a8af5bcf8908633750645198b1c373be6c6ea9db31","node-v14.15.4.tar.gz":"8610d81b2d4afc3a79afbe6209d510125131c45cae22cac63bb767dcfec1cbf0","node-v14.15.4.tar.xz":"adb7ecf66c74b52a14a08cc22bb0f9aedc157cac1ac93240f7f455e8c8edec9c","node-v14.15.4-win-x64.7z":"1da86f92f158e53ee79469daf5e6a3e3f2e6e7c233bbf4b91ab12e1ca9503444","node-v14.15.4-win-x64.zip":"b2a0765240f8fbd3ba90a050b8c87069d81db36c9f3745aff7516e833e4d2ed6","node-v14.15.4-win-x86.7z":"e631956bbf65cb046c7d38d0f0a4633755e86df1ff5f37c3610d55f706c1f0c0","node-v14.15.4-win-x86.zip":"49b2ee6106192894809ce14a2932dca41a6bcf5602ce19413fcb3a477f8613b2","node-v14.15.4-x64.msi":"346a053dcd7508f1e5fbb2da0e34cbb3da206ab2439c4bab5a219c3b75e62475","node-v14.15.4-x86.msi":"2e91ec4aca9bccf105d920bf46b4fbe219aa9dd5439e006f65dc426273cbbdfa","win-x64/node.exe":"dc105951e62ca3be85b6d42ce1db5dc0fce6adac90c76861d9e62302a43ac6b6","win-x64/node.lib":"632ef6fd3d8e23c8b333e0dde5a802c80e5bb08e572ac184d9c8ebf47db2be96","win-x64/node_pdb.7z":"79aaa8027f4e98bfc3448d2282dde4678bbb345c1639eae2380ffc9d81ee4581","win-x64/node_pdb.zip":"54ab0ed636dffac1335b7ac29e045ace732f6eef513fa2c549f6a00e367ecdcc","win-x86/node.exe":"89ceec9ba49002797ab4f0e9753f4eae9f415d773aaf65b41b15640a4313d407","win-x86/node.lib":"a6670b0a10985f58d1a66467041926060c16cc6932d3ba490a020f4cb3fd6280","win-x86/node_pdb.7z":"ed7d37ade431e53738d6ef1481a05ad1cfcbea1aaa20289a134a43b01cdcc5b5","win-x86/node_pdb.zip":"81f8634988510fd63fb85eb8ade339c252ce35d8b0a5620b6046e29061b00f87"}
gyp verb download contents checksum {"node-v14.15.4-headers.tar.gz":"3eb7d4ec4964b10a48987c35c37b3e7720735cf3b9806fe40a805fa1d49a9c7d"}
gyp verb validating download checksum for node-v14.15.4-headers.tar.gz (3eb7d4ec4964b10a48987c35c37b3e7720735cf3b9806fe40a805fa1d49a9c7d == 3eb7d4ec4964b10a48987c35c37b3e7720735cf3b9806fe40a805fa1d49a9c7d)
gyp verb get node dir target node version installed: 14.15.4
gyp verb build dir attempting to create "build" dir: /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/.node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/runner/.node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/runner/.node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/runner/.node-gyp/14.15.4
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:10: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
binding.target.mk:126: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: Leaving directory '/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-1039-azure
gyp ERR! command "/usr/local/bin/node" "/home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/runner/work/voidstone-wars/voidstone-wars/node_modules/node-sass
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-05T07_07_35_348Z-debug.log
Error: Process completed with exit code 1.
```
</details>

Applying workaround from https://github.com/sass/node-sass/issues/2010#issuecomment-392717521 seems to help.

**Comment by matejdro** [comment]
Sorry, this appears to be an issue with my own node modules.
