### ISSUE TITLE
highlight_alias.js Error: EACCES: permission denied, open 'highlight_alias.json'

### ISSUE THREAD

**Issue by lozn00** [sma11black/hexo-action#31]
`ithub.com:22 SSH-2.0-159e461a3
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
> hexo-util@3.3.0 postinstall /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-util
> npm run build:highlight
> hexo-util@3.3.0 build:highlight /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-util
> node scripts/build_highlight_alias.js
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: EACCES: permission denied, open 'highlight_alias.json'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'highlight_alias.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-util@3.3.0 build:highlight: `node scripts/build_highlight_alias.js`
npm ERR! Exit status 1
npm ERR! `

**Comment by QyInvoLing** [comment]
Use `QyInvoLing/hexo-action@1.0.6` instead and wait the author accept the PR
